# Generated by Django 5.2.10 on 2026-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab', 'Lab Report'), ('diagnosis', 'Diagnosis'), ('imaging', 'Imaging Report'), ('procedure', 'Procedure Notes'), ('consultation', 'Consultation'), ('follow-up', 'Follow-up Notes')], max_length=20)),
                ('diagnosis', models.CharField(max_length=500)),
                ('notes', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='medical_documents/')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
