# Generated by Django 5.2.10 on 2026-02-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='ipfs_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for the medical document', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ipfs_metadata_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for record metadata', max_length=100, null=True),
        ),
    ]
