# Generated by Django 5.2.10 on 2026-02-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='certificate_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for uploaded certificate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for doctor profile metadata', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for patient profile metadata', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blockchain_id',
            field=models.CharField(blank=True, help_text='SHA256 hash serving as blockchain identity', max_length=64, null=True, unique=True),
        ),
    ]
