# Generated by Django 6.0.1 on 2026-02-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_certificate_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id_requested', models.CharField(blank=True, help_text='Doctor ID if specific doctor was requested but not found', max_length=20)),
                ('access_type', models.CharField(choices=[('FULL', 'Full Access'), ('TEMPORARY', 'Temporary (30 days)'), ('EMERGENCY', 'Emergency Only')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REVOKED', 'Revoked')], default='APPROVED', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='If null, this is a general access grant (any doctor can request)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_received', to='users.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_sent', to='users.patientprofile')),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
