# Generated by Django 6.0.1 on 2026-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture image', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture image', null=True, upload_to='profile_pictures/'),
        ),
    ]
